### ISSUE TITLE
Create database class

### ISSUE THREAD

**Issue by beumerr** [beumerr/quaco#7]
Location: **src/admin/classes/quaco-db.php** 

**Requirements:**
 - Use mysql**i**
 - Always prepare values

**Tips:**
 - WordPress created a pretty genius [database class](https://codex.wordpress.org/Class_Reference/wpdb), check it out

**Globals for db connection:**
 - $db_name
 - $db_host
 - $db_pass
 - $db_charset

**'*' = method contains parameters**

**Methodes:**
- [x] constructor -> check / create connection to DB 
- [x] get_last_id -> returns ID from last insert
- [x] _construct -> set db vars
- [x] db_connect -> Init db connection
- [x] prepare -> Prepares a SQL query for safe execution. Uses sprintf()-like syntax.
    - [x] placeholder_escape ->Generates and returns a placeholder escape string for use in queries 
           returned by ::prepare()
     - [x] add_placeholder_escape ->Adds a placeholder escape string, to escape anything that 
           resembles a printf()
     - [x] remove_placeholder_escape ->Removes the placeholder escape strings from a query.
- [x] get_var -> execute select query, returning 1 value *
- [x] get_row -> execute select query, returning row *
- [x] get_table -> execute select query, returning table *
- [x] delete -> execute delete query *
- [x] update -> execute update query * 
- [x] insert -> execute insert query *
- [x] query -> execute any query  *
